export const questions = [
  {
    id: 1,
    field: "continuaSemFinanceiro",
    question:
      "No momento, estamos dando prioridade a demandas com benefícios financeiros e operacionais com cálculo dos ganhos esperados. Caso a demanda não possua benefícios financeiros a mesma deve ser alinhada previamente com o diretor da área antes de ser realizada esta solicitação. Pediremos mais a frente o e-mail com o De acordo do Diretor. Deseja prosseguir?",
    type: "boolean",
    next: { SIM: 2, NAO: "END" },
  },
  {
    id: 2,
    field: "possuiGanhoFinanceiro",
    question: "Sua solicitação possui ganho/retorno financeiro?",
    type: "boolean",
    next: { SIM: 3, NAO: 6 },
  },
  {
    id: 3,
    field: "valorGanho",
    question: "Qual o ganho/retorno financeiro anual esperado?",
    type: "number",
    next: 4,
  },
  {
    id: 4,
    field: "possuiCalculoFinanceiro",
    question: "Possui o cálculo que apresente como chegou ao valor informado?",
    type: "boolean",
    next: { SIM: 5, NAO: 11 },
  },
  {
    id: 5,
    field: "arquivoCalculoFinanceiro",
    question: "Envie o arquivo com o cálculo financeiro",
    type: "file",
    next: 7,
  },
  {
    id: 6,
    field: "ehBug",
    question:
      "FILA EXCLUSIVA PARA TRATAMENTO DE BUGS: Esta demanda trata-se de um ajuste sistêmico para algum dos seguintes sistemas? SAE, Autonomy, SSI, OSP Control, GAUS, SLICE. Demandas de melhorias/evolutivas cadastradas nesse item serão canceladas.",
    type: "boolean",
    next: { SIM: "END", NAO: 7 },
  },
  {
    id: 7,
    field: "envolveIntegracao",
    question:
      "Esta demanda envolve alteração sistêmica ou integração (APIs, sistemas, etc)?",
    type: "boolean",
    next: { SIM: 8, NAO: 6 },
  },
  {
    id: 8,
    field: "alinhadoDiretor",
    question: "Esta demanda foi alinhada com o diretor da área?",
    type: "boolean",
    next: { SIM: 9, NAO: 10 },
  },
  {
    id: 9,
    field: "emailDiretor",
    question: "Informe o e-mail com o de acordo do diretor",
    type: "text",
    next: "UPLOAD_DOC",
  },
  {
    id: "UPLOAD_DOC",
    field: "documentoDiretor",
    question: "Envie o documento de aprovação do diretor",
    type: "file",
    next: 12,
  },
  {
    id: 10,
    field: "erroDiretor",
    question: "Por favor, alinhe com o diretor antes de seguir com a demanda.",
    type: "info",
    next: "END",
  },
  {
    id: 11,
    field: "erroFinanceiro",
    question:
      "Por favor, levante o cálculo financeiro e abra uma nova solicitação.",
    type: "info",
    next: "END",
  },
  {
    id: 12,
    field: "possuiGanhoOperacional",
    question: "A solicitação possui ganhos operacionais?",
    type: "boolean",
    next: { SIM: 13, NAO: 17 },
  },
  {
    id: 13,
    field: "descricaoGanhosOperacionais",
    question: "Quais são os ganhos operacionais?",
    type: "text",
    multiline: true,
    next: 14,
  },
  {
    id: 14,
    field: "possuiCalculoOperacional",
    question: "Possui cálculo dos ganhos operacionais?",
    type: "boolean",
    next: { SIM: 16, NAO: 15 },
  },
  {
    id: 15,
    field: "erroOperacional",
    question: "Por favor, levante o cálculo operacional antes de seguir.",
    type: "info",
    next: "END",
  },
  {
    id: 16,
    field: "arquivoOperacional",
    question: "Envie o cálculo operacional",
    type: "file",
    next: 17,
  },
  {
    id: 17,
    field: "possuiQualitativo",
    question: "Possui ganhos qualitativos?",
    type: "boolean",
    next: { SIM: 18, NAO: "FINAL" },
  },
  {
    id: 18,
    field: "descricaoQualitativo",
    question: "Descreva os benefícios qualitativos",
    type: "text",
    multiline: true,
    next: 19,
  },
  {
    id: 19,
    field: "detalheQualitativo",
    question: "Detalhe melhor os benefícios qualitativos",
    type: "text",
    multiline: true,
    next: 20,
  },
  {
    id: 20,
    field: "possuiDados",
    question: "Você possui dados para validar os ganhos esperados?",
    type: "boolean",
    next: { SIM: 22, NAO: 21 },
  },
  {
    id: 21,
    field: "erroDados",
    question: "Por favor, levante os dados antes de abrir a demanda.",
    type: "info",
    next: "END",
  },
  {
    id: 22,
    field: "cenarioAtual",
    question: "Informe os dados atuais/cenário",
    type: "text",
    multiline: true,
    next: "FINAL",
  },
  {
    id: "FINAL",
    field: "finalizacao",
    question: "Deseja salvar a demanda?",
    type: "confirm",
    next: "SAVE",
  },
];
 